name: Sanity Check

on:
  pull_request:
  push:
    branches:
      - 'release/**'

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - uses: meta-introspector/checkout@v4
      - uses: meta-introspector/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
